### ISSUE TITLE
Use Electron IPC for Sandbox

### ISSUE THREAD

**Issue by DaQuirm** [DaQuirm/css-quickdraw-redux#141]
- [ ] Create a Warp Transport for Electron IPC
- [ ] Make sure all Warp clients play nice together
- [x] Migrate from Nightmare to bare Electron
- [ ] Clean-up auth and stuff like that
- [ ] Enjoy _epic_ performance 😸

**Comment by R1ZZU** [comment]
actually we can't use electron IPC, as it's available only in electron main/renderer processes 😿 
we can't start electron with `ChildProcess.fork` as well, as `electron-prebuilt` isn't smth from node world, but os executable...

**Comment by DaQuirm** [comment]
Well, looks like it cannot be done then 😿
