### ISSUE TITLE
Solution time in players list is not aligned properly

### ISSUE THREAD

**Issue by DaQuirm** [DaQuirm/css-quickdraw-redux#168]
When players' names have different length 
![pasted image at 2016_05_01 03_56 pm](https://cloud.githubusercontent.com/assets/669784/14970399/dc851522-10c8-11e6-80d0-378684d4e039.png)

**Comment by kirilknysh** [comment]
Should be fixed in scope of https://github.com/DaQuirm/css-quickdraw-redux/pull/162
