### ISSUE TITLE
Score update after "Stop round"

### ISSUE THREAD

**Issue by R1ZZU** [DaQuirm/css-quickdraw-redux#172]
stop round always add 2 minutes to disconnected players, even if player have solved round before disconnect

1. Start GM
2. Start G
3. GM starts round K
4. G solves round K for N sec
5. G disconnects (closes the tab)
6. GM stops round K
7. GM starts round L
8. G re-connects during round L
9. G solves round L for P sec
10. GM stops round L

Actual: G has aggregate time (2 min + P sec)
Expected: G has aggregate time (N sec + P sec)

**Comment by kirilknysh** [comment]
Still reproducible
